//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trianz.Enterprise.Operations.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssessorIntrayComment
    {
        public long AssessorIntrayCommentId { get; set; }
        public long AssesseeIntrayDataID { get; set; }
        public long AssessmentID { get; set; }
        public long AssessmentWorkflowId { get; set; }
        public Nullable<long> IntrayID { get; set; }
        public string IntrayName { get; set; }
        public string IntrayDescription { get; set; }
        public string AssessorComment { get; set; }
        public Nullable<System.DateTime> AssessorCommentDate { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedBy { get; set; }
    }
}
