//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trianz.Enterprise.Operations.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BuddyReferral
    {
        public int ReferralId { get; set; }
        public string Name { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public long PhoneNumber { get; set; }
        public string EmailAddress { get; set; }
        public int ReferBy { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string PAN { get; set; }
        public string Skills { get; set; }
        public string HRRFID { get; set; }
        public string filename { get; set; }
        public Nullable<int> YearsOfExperience { get; set; }
        public Nullable<int> MonthsOfExperience { get; set; }
        public byte[] DocumentContent { get; set; }
        public string ContentType { get; set; }
        public string Status { get; set; }
        public string Address { get; set; }
        public string Location { get; set; }
        public string MappedTRNumber { get; set; }
        public Nullable<int> ReasonForRejection { get; set; }
        public Nullable<System.DateTime> ReferredDate { get; set; }
    }
}
