//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trianz.Enterprise.Operations.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CareersJobApplication
    {
        public long ApplicationId { get; set; }
        public Nullable<int> UserId { get; set; }
        public string TrNumber { get; set; }
        public Nullable<System.DateTime> AppliedDate { get; set; }
        public string Status { get; set; }
        public Nullable<int> ReasonForRejection { get; set; }
        public string OtherReason { get; set; }
    }
}
