//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trianz.Enterprise.Operations.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientTimesheetItems
    {
        public int ClientTimesheetID { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public string ProjectCode { get; set; }
        public Nullable<System.DateTime> ItemDate { get; set; }
        public Nullable<decimal> Hours { get; set; }
        public Nullable<int> UploadedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<System.DateTime> SyncDate { get; set; }
        public Nullable<bool> IsAdjustmentMode { get; set; }
        public Nullable<bool> AdjustmentStatus { get; set; }
        public Nullable<bool> AdjustmentFlag { get; set; }
    }
}
