//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trianz.Enterprise.Operations.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClusterLeadTeam
    {
        public long ClusterLeadTeamID { get; set; }
        public long ClusterSkillLeadID { get; set; }
        public int TeamMemberID { get; set; }
    }
}
