//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trianz.Enterprise.Operations.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CurioProject
    {
        public int ProjectID { get; set; }
        public string ProjectCode { get; set; }
        public string ProjectName { get; set; }
        public string Department { get; set; }
        public string ProjectManager { get; set; }
        public string Task { get; set; }
        public Nullable<int> ExpOrg { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string Task_Name { get; set; }
        public Nullable<int> Task_ID { get; set; }
        public Nullable<int> Project_ID { get; set; }
        public string ProjectType { get; set; }
    }
}
