//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trianz.Enterprise.Operations.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmailAudit
    {
        public int ID { get; set; }
        public Nullable<int> ToMailEmpId { get; set; }
        public Nullable<int> RresourceEmpID { get; set; }
        public string MailSubject { get; set; }
        public string Mailbody { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string MailSent { get; set; }
    }
}
