//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trianz.Enterprise.Operations.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeEngagement
    {
        public int EngagementID { get; set; }
        public int Employeeid { get; set; }
        public int HRBPID { get; set; }
        public System.DateTime DateofMeet { get; set; }
        public string AttritionRisk { get; set; }
        public int AreaofFocusID { get; set; }
        public string ConcernsRaised { get; set; }
        public string ConcernsUpdate { get; set; }
        public string ConcernsStatus { get; set; }
        public string Remarks { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> ClosedOn { get; set; }
        public Nullable<int> ModifiedBY { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string UploadAttachment { get; set; }
    }
}
