//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trianz.Enterprise.Operations.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeRelieving
    {
        public int RelievingID { get; set; }
        public int EmployeeID { get; set; }
        public int ReasonID { get; set; }
        public System.DateTime DateofResignation { get; set; }
        public Nullable<System.DateTime> RequestedRelievingDate { get; set; }
        public string Reason { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string DocumentName { get; set; }
        public string ContentType { get; set; }
        public Nullable<decimal> DocumentSize { get; set; }
        public byte[] DocumentContent { get; set; }
        public string SupervisorFeedback1 { get; set; }
        public string SupervisorFeedback2 { get; set; }
        public string RetentionScale { get; set; }
        public string HRFeedback1 { get; set; }
        public string HRFeedback2 { get; set; }
        public Nullable<bool> IsNoticeperiodwaiver { get; set; }
        public Nullable<System.DateTime> HRRequestedRelievingDate { get; set; }
        public string WaiverDetails { get; set; }
        public string Status { get; set; }
        public string ReasonInDetail { get; set; }
        public string IsEmployeeRetaining { get; set; }
        public string PersonalEmail { get; set; }
        public string ContactNumber { get; set; }
        public string RetentionJustification { get; set; }
        public string HRComments { get; set; }
        public string HRDocumentName { get; set; }
        public string HRContentType { get; set; }
        public Nullable<decimal> HRDocumentSize { get; set; }
        public byte[] HRDocumentContent { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> Modified_Date { get; set; }
        public string AttritionType { get; set; }
        public string WorkForceAttrition { get; set; }
        public string Rehire { get; set; }
        public string ReasonForRehire { get; set; }
        public Nullable<System.DateTime> DateOfRelieving { get; set; }
        public Nullable<bool> IsImmediateTermination { get; set; }
    }
}
