//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trianz.Enterprise.Operations.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeSkills_New
    {
        public int EmployeeSkillId { get; set; }
        public int EmployeeId { get; set; }
        public int SkillId { get; set; }
        public string Expertiselevel { get; set; }
        public string TechnologyLastUsed { get; set; }
        public string SkillStatus { get; set; }
        public Nullable<int> ApproverId { get; set; }
        public Nullable<System.DateTime> ApprovalDate { get; set; }
        public System.DateTime LastModifiedDate { get; set; }
        public string Remarks { get; set; }
        public Nullable<bool> IsPrimary { get; set; }
        public Nullable<bool> IsReviewed { get; set; }
        public Nullable<int> ReviewerId { get; set; }
        public Nullable<System.DateTime> LastReviewdDate { get; set; }
        public Nullable<System.DateTime> ApprovalSubmissionDate { get; set; }
    }
}
