//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trianz.Enterprise.Operations.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EXCHANGERATE
    {
        public int RATEID { get; set; }
        public string SRCCURR { get; set; }
        public string DESTCURR { get; set; }
        public Nullable<int> RATE { get; set; }
        public Nullable<System.DateTime> RATEDATE { get; set; }
    }
}
