//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trianz.Enterprise.Operations.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExternalFulfillment
    {
        public long ExternalFulfilID { get; set; }
        public string HRRFNumber { get; set; }
        public string ProjectName { get; set; }
        public string ProjectCode { get; set; }
        public string Role { get; set; }
        public Nullable<int> Grade { get; set; }
        public string Skills { get; set; }
        public string Practice { get; set; }
        public string Location { get; set; }
        public string Account { get; set; }
        public string ApprovalStatus { get; set; }
        public string Remarks { get; set; }
        public string RequestedBy { get; set; }
        public Nullable<System.DateTime> RequestedDate { get; set; }
        public string ApprovedBy { get; set; }
        public Nullable<System.DateTime> ApprovedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<long> HRRFID { get; set; }
    
        public virtual HRRF HRRF { get; set; }
    }
}
