//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trianz.Enterprise.Operations.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HROneonOneHistory
    {
        public int HistoryID { get; set; }
        public int EngagementID { get; set; }
        public string ConcernsRaised { get; set; }
        public string ConcernsUpdate { get; set; }
        public string ConcernsStatus { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.DateTime> ClosedOn { get; set; }
        public Nullable<int> Updatedby { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    }
}
