//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trianz.Enterprise.Operations.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HRRFAudit
    {
        public int HistoryID { get; set; }
        public long HRRFID { get; set; }
        public string HRRFNumber { get; set; }
        public string Purpose { get; set; }
        public string ProjectName { get; set; }
        public string ProjectCode { get; set; }
        public Nullable<int> Grade { get; set; }
        public string RoleRequired { get; set; }
        public Nullable<System.DateTime> AssignmentStartDate { get; set; }
        public Nullable<System.DateTime> AssignmentEndDate { get; set; }
        public string LocationType { get; set; }
        public string LocationName { get; set; }
        public string Practice { get; set; }
        public string AccountName { get; set; }
        public string CostCenter { get; set; }
        public string ResourceType { get; set; }
        public string EnagagementType { get; set; }
        public string DemandType { get; set; }
        public string JobDescription { get; set; }
        public string RequestReason { get; set; }
        public string Criticality { get; set; }
        public string Utilization { get; set; }
        public Nullable<System.DateTime> BillingDate { get; set; }
        public string PurposeNew { get; set; }
        public string ProjectNameNew { get; set; }
        public string ProjectCodeNew { get; set; }
        public Nullable<int> GradeNew { get; set; }
        public string RoleRequiredNew { get; set; }
        public Nullable<System.DateTime> AssignmentStartDateNew { get; set; }
        public Nullable<System.DateTime> AssignmentEndDateNew { get; set; }
        public string LocationTypeNew { get; set; }
        public string LocationNameNew { get; set; }
        public string PracticeNew { get; set; }
        public string AccountNameNew { get; set; }
        public string CostCenterNew { get; set; }
        public string ResourceTypeNew { get; set; }
        public Nullable<System.DateTime> BillingDateNew { get; set; }
        public string EnagagementTypeNew { get; set; }
        public string DemandTypeNew { get; set; }
        public string JobDescriptionNew { get; set; }
        public string RequestReasonNew { get; set; }
        public string CriticalityNew { get; set; }
        public string UtilizationNew { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<bool> IsContracting { get; set; }
        public Nullable<bool> IsContractingNew { get; set; }
        public string Impact { get; set; }
        public string ImpactNew { get; set; }
        public string IMP { get; set; }
        public string Discipline { get; set; }
        public string RoleGroup { get; set; }
        public string CoreSkill { get; set; }
        public string IntermediateSkill { get; set; }
        public string AdvancedSkill { get; set; }
        public string SpecificPlatform { get; set; }
        public string Certifications { get; set; }
        public Nullable<bool> IsSpecialClient { get; set; }
        public Nullable<bool> IsIndustryDomainSkill { get; set; }
        public string SpecialClient { get; set; }
        public string IndustryDomainSkill { get; set; }
        public string DisciplineNew { get; set; }
        public string RoleGroupNew { get; set; }
        public string CoreSkillNew { get; set; }
        public string IntermediateSkillNew { get; set; }
        public string AdvancedSkillNew { get; set; }
        public string SpecificPlatformNew { get; set; }
        public string CertificationsNew { get; set; }
        public Nullable<bool> IsSpecialClientNew { get; set; }
        public Nullable<bool> IsIndustryDomainSkillNew { get; set; }
        public string SpecialClientNew { get; set; }
        public string IndustryDomainSkillNew { get; set; }
    }
}
