//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trianz.Enterprise.Operations.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HRRF
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HRRF()
        {
            this.ExternalFulfillments = new HashSet<ExternalFulfillment>();
            this.ExternalHires = new HashSet<ExternalHire>();
            this.ProposeAssociates = new HashSet<ProposeAssociate>();
        }
    
        public long HRRFID { get; set; }
        public string HRRFNumber { get; set; }
        public string Purpose { get; set; }
        public string ProjectName { get; set; }
        public string ProjectCode { get; set; }
        public string OpportunityName { get; set; }
        public string OpportunityCode { get; set; }
        public string DemandType { get; set; }
        public Nullable<int> Grade { get; set; }
        public string RoleRequired { get; set; }
        public string ExpFrom { get; set; }
        public string ExpTo { get; set; }
        public string EnagagementType { get; set; }
        public string ResourceName { get; set; }
        public string Domain { get; set; }
        public string JobDescription { get; set; }
        public Nullable<System.DateTime> AssignmentStartDate { get; set; }
        public Nullable<System.DateTime> AssignmentEndDate { get; set; }
        public string LocationType { get; set; }
        public string LocationName { get; set; }
        public string RequestReason { get; set; }
        public string Remarks { get; set; }
        public string RequestType { get; set; }
        public string RequestStatus { get; set; }
        public string ClientInterview { get; set; }
        public Nullable<bool> CallCompleted { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> HRRFCreatedBy { get; set; }
        public Nullable<System.DateTime> HRRFCreatedDate { get; set; }
        public Nullable<System.DateTime> HRRFSubmitedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> Positions { get; set; }
        public string Practice { get; set; }
        public string TRParent { get; set; }
        public Nullable<bool> Isparent { get; set; }
        public string VisaType { get; set; }
        public string AccountName { get; set; }
        public string OldHRRFNumber { get; set; }
        public string CostCenter { get; set; }
        public Nullable<int> ReplacementEmpId { get; set; }
        public string ResourceType { get; set; }
        public Nullable<bool> IsContracting { get; set; }
        public string Criticality { get; set; }
        public string Utilization { get; set; }
        public Nullable<System.DateTime> BillingDate { get; set; }
        public Nullable<System.DateTime> InternalExpectedFulfilmentDate { get; set; }
        public string CancelReason { get; set; }
        public string DuplicateHRRFNo { get; set; }
        public string TECHPANEL { get; set; }
        public string SECONDTECHPANEL { get; set; }
        public string OpportunitySalestage { get; set; }
        public string RequisitionID { get; set; }
        public Nullable<int> employeeid { get; set; }
        public string Impact { get; set; }
        public string Skill { get; set; }
        public string JDSUMMARY { get; set; }
        public string RefBonus { get; set; }
        public string HRNGMGRID { get; set; }
        public string HRNGMGR { get; set; }
        public string RECRTR { get; set; }
        public string RCIMPACT { get; set; }
        public string SpecialClient { get; set; }
        public string ShiftTime { get; set; }
        public string Discipline { get; set; }
        public string RoleGroup { get; set; }
        public string CoreSkill { get; set; }
        public string IntermediateSkill { get; set; }
        public string AdvancedSkill { get; set; }
        public string SpecificPlatform { get; set; }
        public string Certifications { get; set; }
        public Nullable<bool> IsSpecialClient { get; set; }
        public Nullable<bool> IsIndustryDomainSkill { get; set; }
        public string IndustryDomainSkill { get; set; }
        public string SkillCluster { get; set; }
        public string SkillCode { get; set; }
        public string CSKILL { get; set; }
        public string CLSTRDESC { get; set; }
        public string CLSTRJD { get; set; }
        public string PrimaryPractice { get; set; }
        public string JDNotMatching { get; set; }
        public string ExternalWebSite { get; set; }
        public string UPDATEEXTERNAL { get; set; }
        public Nullable<decimal> BILLRATE { get; set; }
        public Nullable<System.DateTime> FulfillmentDate { get; set; }
        public Nullable<System.DateTime> CancellationDate { get; set; }
        public Nullable<double> MAXSAL { get; set; }
        public string OrganizationGroup { get; set; }
        public string SkillCode_WIP { get; set; }
        public string Organization_SubGroup { get; set; }
        public Nullable<int> BOSPOC { get; set; }
        public string ReasonRaisingTR { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExternalFulfillment> ExternalFulfillments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExternalHire> ExternalHires { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProposeAssociate> ProposeAssociates { get; set; }
    }
}
