//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trianz.Enterprise.Operations.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HRWarningRemarks
    {
        public int HRWarningID { get; set; }
        public int EmployeeID { get; set; }
        public int ProjectManagerID { get; set; }
        public string WarningRemarks { get; set; }
        public Nullable<int> HRBPID { get; set; }
        public bool IsWarningLetterIssued { get; set; }
        public Nullable<System.DateTime> WarningLetterIssuedDate { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string DocumentName { get; set; }
        public string ContentType { get; set; }
        public Nullable<decimal> DocumentSize { get; set; }
        public byte[] DocumentContent { get; set; }
        public string HRBPComments { get; set; }
        public string Status { get; set; }
    }
}
