//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trianz.Enterprise.Operations.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NumberingSystem
    {
        public int ID { get; set; }
        public string CompanyCode { get; set; }
        public string BranchCode { get; set; }
        public string SequenceSuffix { get; set; }
        public string SequenceNumber { get; set; }
        public string TypeCode { get; set; }
        public Nullable<bool> IncludeCompanyCode { get; set; }
        public Nullable<bool> IncludeBranchCode { get; set; }
        public Nullable<bool> IncludeSequenceSuffix { get; set; }
        public Nullable<bool> IncludeDate { get; set; }
        public Nullable<bool> IncludeTypeCode { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public string ChangedBy { get; set; }
        public Nullable<System.DateTime> DateChanged { get; set; }
        public Nullable<long> OrderNum { get; set; }
    }
}
