//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trianz.Enterprise.Operations.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PerformanceFeedbackAcitivity
    {
        public long FeedbackActivityId { get; set; }
        public long FeedbackId { get; set; }
        public System.DateTime ActivityDate { get; set; }
        public string ActivityDesc { get; set; }
        public int ActivityBy { get; set; }
    }
}
