//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trianz.Enterprise.Operations.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectAssignmentsDel
    {
        public int DeleteAssignment_Id { get; set; }
        public int Assignment_Id { get; set; }
        public string ProjectName { get; set; }
        public int ProjectID { get; set; }
        public Nullable<int> EmployeeId { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<int> Utilization { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string Assigned_By { get; set; }
        public Nullable<System.DateTime> Assigned_Date { get; set; }
        public string ProjectCode { get; set; }
        public string BillingStatus { get; set; }
        public string Category { get; set; }
        public string Bechstatus { get; set; }
        public string Customer { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.DateTime> ExpectedBillingDate { get; set; }
        public Nullable<System.DateTime> MappedDate { get; set; }
        public string HRRFNumber { get; set; }
        public Nullable<System.DateTime> ActionReminder { get; set; }
        public string ReservedProjectCode { get; set; }
        public string OPsStatus { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string PRMStatusCode { get; set; }
        public Nullable<System.DateTime> ReleaseDate { get; set; }
        public string ClientorProject { get; set; }
        public string ReasonForRelease { get; set; }
        public string SkillsGoodAt { get; set; }
        public string DetailedFeedBack { get; set; }
        public string ResourcePerformance { get; set; }
        public Nullable<int> ReleasedBy { get; set; }
        public Nullable<System.DateTime> ReleaseAuditDate { get; set; }
        public string IsDiscResourceOnProject { get; set; }
        public string OrganisationGroup { get; set; }
        public string OrganisationSubGroup { get; set; }
        public string Deleted_By { get; set; }
        public Nullable<System.DateTime> Deleted_Date { get; set; }
    }
}
