//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trianz.Enterprise.Operations.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project
    {
        public int ProjectId { get; set; }
        public string ProjectCode { get; set; }
        public string ProjectName { get; set; }
        public Nullable<System.DateTime> SOWStartDate { get; set; }
        public Nullable<System.DateTime> SOWEndDate { get; set; }
        public string AccountName { get; set; }
        public string ClientManager { get; set; }
        public string ProjectManager { get; set; }
        public Nullable<int> OnsiteHeadCount { get; set; }
        public Nullable<int> OffshoreHeadCount { get; set; }
        public Nullable<int> HeadCount { get; set; }
        public string SOWStatus { get; set; }
        public string Category { get; set; }
        public string BillingType { get; set; }
        public string EngagementType { get; set; }
        public Nullable<double> SOWAmount { get; set; }
        public string Comments { get; set; }
        public bool IsActive { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<int> ProjectManagerId { get; set; }
        public string ServiceLine { get; set; }
        public string DeliveryHead { get; set; }
        public string DeliveryManager { get; set; }
        public Nullable<int> DELIVERY_HEAD_ID { get; set; }
        public Nullable<int> DELIVERY_MANAGER_ID { get; set; }
        public string COST_CENTER { get; set; }
        public string ENGAGEMENT_DIRECTOR_NAME { get; set; }
        public Nullable<int> ENGAGEMENT_DIRECTOR_ID { get; set; }
        public string PROJECT_PRACTICE { get; set; }
        public string Project_Sub_Type { get; set; }
        public string AliasPrjName { get; set; }
        public string AliasAccName { get; set; }
        public Nullable<int> BOSPOC { get; set; }
    }
}
