//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trianz.Enterprise.Operations.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProposeAssociate
    {
        public long ProposedID { get; set; }
        public string HRRFNumber { get; set; }
        public string EmpID { get; set; }
        public string EmpName { get; set; }
        public string ProjectName { get; set; }
        public string ProjectCode { get; set; }
        public string EmpRole { get; set; }
        public string Grade { get; set; }
        public string Skills { get; set; }
        public string Practice { get; set; }
        public string DeliveryStatus { get; set; }
        public string DeliveryRemarks { get; set; }
        public string PracticeStatus { get; set; }
        public string PracticeRemarks { get; set; }
        public string ProposedBy { get; set; }
        public Nullable<System.DateTime> ProposedDate { get; set; }
        public string ApprovedBy { get; set; }
        public Nullable<System.DateTime> ApprovedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<long> HRRFID { get; set; }
    
        public virtual HRRF HRRF { get; set; }
    }
}
