//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trianz.Enterprise.Operations.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SecuraxEmployeeHrs
    {
        public string EmployeeId { get; set; }
        public Nullable<System.DateTime> PunchDate { get; set; }
        public Nullable<System.TimeSpan> PunchInTime { get; set; }
        public Nullable<System.TimeSpan> PunchOutTime { get; set; }
        public Nullable<System.TimeSpan> WorkHrsPerday { get; set; }
        public string Status { get; set; }
        public Nullable<System.TimeSpan> OT { get; set; }
        public Nullable<int> Created_By { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public Nullable<int> Modified_By { get; set; }
        public Nullable<System.DateTime> Modified_Date { get; set; }
        public int S_Id { get; set; }
    }
}
