//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trianz.Enterprise.Operations.Models
{
    using System;
    
    public partial class sp_GetHRRFListByEmpIdPractice_Result2
    {
        public string HRRFNumber { get; set; }
        public string JobDescription { get; set; }
        public string Purpose { get; set; }
        public string Project { get; set; }
        public string Practice { get; set; }
        public string RoleRequired { get; set; }
        public string LocationName { get; set; }
        public Nullable<System.DateTime> HRRFSubmitedDate { get; set; }
        public string RequestStatus { get; set; }
        public string RequestType { get; set; }
        public string ResourceName { get; set; }
        public long HRRFID { get; set; }
    }
}
