//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trianz.Enterprise.Operations.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TimesheetComment
    {
        public long TimesheetCommentId { get; set; }
        public long TimesheetID { get; set; }
        public Nullable<System.DateTime> CommentedDate { get; set; }
        public string Comments { get; set; }
    
        public virtual Timesheet Timesheet { get; set; }
    }
}
