//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trianz.Enterprise.Operations.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TimesheetItem
    {
        public int TimesheetItemID { get; set; }
        public string ProjectCode { get; set; }
        public string Task { get; set; }
        public Nullable<bool> IsBillable { get; set; }
        public Nullable<decimal> Mon { get; set; }
        public Nullable<decimal> Tue { get; set; }
        public Nullable<decimal> Wed { get; set; }
        public Nullable<decimal> Thu { get; set; }
        public Nullable<decimal> Fri { get; set; }
        public Nullable<decimal> Sat { get; set; }
        public Nullable<decimal> Sun { get; set; }
        public Nullable<decimal> TotalHours { get; set; }
        public int EmployeeId { get; set; }
        public Nullable<long> TimesheetID { get; set; }
        public Nullable<int> TaskID { get; set; }
        public bool IsGeneral { get; set; }
        public Nullable<int> ApproverID { get; set; }
        public string ItemStatus { get; set; }
        public Nullable<System.DateTime> syncdate { get; set; }
        public Nullable<bool> IsAdjustmentMode { get; set; }
        public Nullable<bool> AdjustmentStatus { get; set; }
        public Nullable<bool> AdjustmentFlag { get; set; }
    }
}
