//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trianz.Enterprise.Operations.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Training
    {
        public int TrainingID { get; set; }
        public string ProgramName { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public int EmployeeID { get; set; }
        public string Location { get; set; }
        public string Practice { get; set; }
        public string AttendanceStatus { get; set; }
        public string Traininghrs { get; set; }
        public string TrainingDays { get; set; }
        public string TotalHours { get; set; }
        public string TrainerName { get; set; }
        public string Source { get; set; }
        public string Category { get; set; }
        public string Mode { get; set; }
        public string Feedbackrating { get; set; }
    }
}
