//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trianz.Enterprise.Operations.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class TrianzOperationsEntities : DbContext
    {
        public TrianzOperationsEntities()
            : base("name=TrianzOperationsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AddtionalWHMPunchInOUT> AddtionalWHMPunchInOUTs { get; set; }
        public virtual DbSet<AgreementTransaction> AgreementTransactions { get; set; }
        public virtual DbSet<Application> Applications { get; set; }
        public virtual DbSet<ApplicationSetting> ApplicationSettings { get; set; }
        public virtual DbSet<AreaofFocu> AreaofFocus { get; set; }
        public virtual DbSet<City> Cities { get; set; }
        public virtual DbSet<CostCenterForImmidart> CostCenterForImmidarts { get; set; }
        public virtual DbSet<Country> Countries { get; set; }
        public virtual DbSet<DepartmentForImmidart> DepartmentForImmidarts { get; set; }
        public virtual DbSet<DesignationMaster> DesignationMasters { get; set; }
        public virtual DbSet<DisciplineMaster> DisciplineMasters { get; set; }
        public virtual DbSet<Domain> Domains { get; set; }
        public virtual DbSet<ELMAH_Error> ELMAH_Error { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<EmployeeAddressInformation> EmployeeAddressInformations { get; set; }
        public virtual DbSet<EmployeeEngagement> EmployeeEngagements { get; set; }
        public virtual DbSet<EmployeeProfile> EmployeeProfiles { get; set; }
        public virtual DbSet<EmployeeSkillHistory> EmployeeSkillHistories { get; set; }
        public virtual DbSet<EmployeeSkill> EmployeeSkills { get; set; }
        public virtual DbSet<EmployeeSkills_New> EmployeeSkills_New { get; set; }
        public virtual DbSet<EmployeeWiseIndustry> EmployeeWiseIndustries { get; set; }
        public virtual DbSet<Error_Info> Error_Info { get; set; }
        public virtual DbSet<ExcludedEmployeeType> ExcludedEmployeeTypes { get; set; }
        public virtual DbSet<ExpertiseLevel> ExpertiseLevels { get; set; }
        public virtual DbSet<ExternalFulfillment> ExternalFulfillments { get; set; }
        public virtual DbSet<ExternalHire> ExternalHires { get; set; }
        public virtual DbSet<GlobalTask> GlobalTasks { get; set; }
        public virtual DbSet<HRRFAudit> HRRFAudits { get; set; }
        public virtual DbSet<HRRFHistory> HRRFHistories { get; set; }
        public virtual DbSet<HRRFSkill> HRRFSkills { get; set; }
        public virtual DbSet<HRRFSkills_ExpertiseLevel> HRRFSkills_ExpertiseLevel { get; set; }
        public virtual DbSet<HRWarningMenu> HRWarningMenus { get; set; }
        public virtual DbSet<IncludedBussinessGroup> IncludedBussinessGroups { get; set; }
        public virtual DbSet<MasterLookUp> MasterLookUps { get; set; }
        public virtual DbSet<Notification> Notifications { get; set; }
        public virtual DbSet<NotificationTo> NotificationToes { get; set; }
        public virtual DbSet<PracticeWiseBenchCode> PracticeWiseBenchCodes { get; set; }
        public virtual DbSet<ProfileRejectionEmailFormat> ProfileRejectionEmailFormats { get; set; }
        public virtual DbSet<Project> Projects { get; set; }
        public virtual DbSet<ProjectTask> ProjectTasks { get; set; }
        public virtual DbSet<ProposeAssociate> ProposeAssociates { get; set; }
        public virtual DbSet<RecruitmentEmploye> RecruitmentEmployes { get; set; }
        public virtual DbSet<RecruitmentRole> RecruitmentRoles { get; set; }
        public virtual DbSet<RoleGroupMaster> RoleGroupMasters { get; set; }
        public virtual DbSet<CandidateIdDump> CandidateIdDumps { get; set; }
        public virtual DbSet<RoleMaster> RoleMasters { get; set; }
        public virtual DbSet<ShiftAllowance> ShiftAllowances { get; set; }
        public virtual DbSet<ShiftAllowanceComment> ShiftAllowanceComments { get; set; }
        public virtual DbSet<ShiftConfiguration> ShiftConfigurations { get; set; }
        public virtual DbSet<state> states { get; set; }
        public virtual DbSet<CareersJobApplication> CareersJobApplications { get; set; }
        public virtual DbSet<CareersPracticeMapping> CareersPracticeMappings { get; set; }
        public virtual DbSet<CareersUsersExperienced> CareersUsersExperienceds { get; set; }
        public virtual DbSet<CurioCostCenter> CurioCostCenters { get; set; }
        public virtual DbSet<CurioLocation> CurioLocations { get; set; }
        public virtual DbSet<CurioProject> CurioProjects { get; set; }
        public virtual DbSet<Menu> Menus { get; set; }
        public virtual DbSet<EmployeeDoc> EmployeeDocs { get; set; }
        public virtual DbSet<Training> Trainings { get; set; }
        public virtual DbSet<Industry> Industries { get; set; }
        public virtual DbSet<EmployeeWiseDomain> EmployeeWiseDomains { get; set; }
        public virtual DbSet<BenchEmployee> BenchEmployees { get; set; }
        public virtual DbSet<TR_CancelReason> TR_CancelReason { get; set; }
        public virtual DbSet<TrackSkillSet> TrackSkillSets { get; set; }
        public virtual DbSet<TeamTrackHistory> TeamTrackHistories { get; set; }
        public virtual DbSet<Timesheet> Timesheets { get; set; }
        public virtual DbSet<Opportunity> Opportunities { get; set; }
        public virtual DbSet<InternalSpecific> InternalSpecifics { get; set; }
        public virtual DbSet<CertificationMaster> CertificationMasters { get; set; }
        public virtual DbSet<SpecificPlatFormMaster> SpecificPlatFormMasters { get; set; }
        public virtual DbSet<AssessorIntrayComment> AssessorIntrayComments { get; set; }
        public virtual DbSet<ShiftMaster> ShiftMasters { get; set; }
        public virtual DbSet<SKILLSADV> SKILLSADVs { get; set; }
        public virtual DbSet<SKILLSCORE> SKILLSCOREs { get; set; }
        public virtual DbSet<SKILLSINTRM> SKILLSINTRMs { get; set; }
        public virtual DbSet<MasterAgreement> MasterAgreements { get; set; }
        public virtual DbSet<LocationWiseBUHR> LocationWiseBUHRs { get; set; }
        public virtual DbSet<SkillMaster> SkillMasters { get; set; }
        public virtual DbSet<PRTCSKILLCLUSTER> PRTCSKILLCLUSTERs { get; set; }
        public virtual DbSet<SKILLCLSTRJD> SKILLCLSTRJDs { get; set; }
        public virtual DbSet<PRTCSKILLCLUSTER_delete> PRTCSKILLCLUSTER_delete { get; set; }
        public virtual DbSet<SKILLCLSTRJD_Delete> SKILLCLSTRJD_Delete { get; set; }
        public virtual DbSet<ProjectAssignmenthistory> ProjectAssignmenthistories { get; set; }
        public virtual DbSet<OrganisationGroup> OrganisationGroups { get; set; }
        public virtual DbSet<ProjectAssignment> ProjectAssignments { get; set; }
        public virtual DbSet<EXCHANGERATE> EXCHANGERATEs { get; set; }
        public virtual DbSet<ProjectAssignmentsDel> ProjectAssignmentsDels { get; set; }
        public virtual DbSet<ClusterMaster> ClusterMasters { get; set; }
        public virtual DbSet<PracticeClusterLead> PracticeClusterLeads { get; set; }
        public virtual DbSet<PracticeMaster> PracticeMasters { get; set; }
        public virtual DbSet<EmailAudit> EmailAudits { get; set; }
        public virtual DbSet<EMPLOYEERATE> EMPLOYEERATEs { get; set; }
        public virtual DbSet<HRRF> HRRFs { get; set; }
        public virtual DbSet<ClusterLeadTeam> ClusterLeadTeams { get; set; }
        public virtual DbSet<HRRFRemark> HRRFRemarks { get; set; }
        public virtual DbSet<HRRFStatusHistory> HRRFStatusHistories { get; set; }
        public virtual DbSet<ProfilesInformation> ProfilesInformations { get; set; }
    
        public virtual ObjectResult<sp_GetHRRFReportByEmpIdPractice_1_Result> sp_GetHRRFReportByEmpIdPractice_1(string practice, string request, string account, Nullable<int> empID)
        {
            var practiceParameter = practice != null ?
                new ObjectParameter("Practice", practice) :
                new ObjectParameter("Practice", typeof(string));
    
            var requestParameter = request != null ?
                new ObjectParameter("Request", request) :
                new ObjectParameter("Request", typeof(string));
    
            var accountParameter = account != null ?
                new ObjectParameter("Account", account) :
                new ObjectParameter("Account", typeof(string));
    
            var empIDParameter = empID.HasValue ?
                new ObjectParameter("EmpID", empID) :
                new ObjectParameter("EmpID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetHRRFReportByEmpIdPractice_1_Result>("sp_GetHRRFReportByEmpIdPractice_1", practiceParameter, requestParameter, accountParameter, empIDParameter);
        }
    
        public virtual ObjectResult<sp_GetTrainingData_Result> sp_GetTrainingData(string programName, string location, string practice, string attendanceStatus, string source, string category, string mode, Nullable<System.DateTime> startDate, Nullable<System.DateTime> endDate)
        {
            var programNameParameter = programName != null ?
                new ObjectParameter("ProgramName", programName) :
                new ObjectParameter("ProgramName", typeof(string));
    
            var locationParameter = location != null ?
                new ObjectParameter("Location", location) :
                new ObjectParameter("Location", typeof(string));
    
            var practiceParameter = practice != null ?
                new ObjectParameter("Practice", practice) :
                new ObjectParameter("Practice", typeof(string));
    
            var attendanceStatusParameter = attendanceStatus != null ?
                new ObjectParameter("AttendanceStatus", attendanceStatus) :
                new ObjectParameter("AttendanceStatus", typeof(string));
    
            var sourceParameter = source != null ?
                new ObjectParameter("Source", source) :
                new ObjectParameter("Source", typeof(string));
    
            var categoryParameter = category != null ?
                new ObjectParameter("Category", category) :
                new ObjectParameter("Category", typeof(string));
    
            var modeParameter = mode != null ?
                new ObjectParameter("Mode", mode) :
                new ObjectParameter("Mode", typeof(string));
    
            var startDateParameter = startDate.HasValue ?
                new ObjectParameter("StartDate", startDate) :
                new ObjectParameter("StartDate", typeof(System.DateTime));
    
            var endDateParameter = endDate.HasValue ?
                new ObjectParameter("EndDate", endDate) :
                new ObjectParameter("EndDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetTrainingData_Result>("sp_GetTrainingData", programNameParameter, locationParameter, practiceParameter, attendanceStatusParameter, sourceParameter, categoryParameter, modeParameter, startDateParameter, endDateParameter);
        }
    
        public virtual int sp_GetHRRFReportByEmpIdPractice(string practice, string request, string account, Nullable<int> empID)
        {
            var practiceParameter = practice != null ?
                new ObjectParameter("Practice", practice) :
                new ObjectParameter("Practice", typeof(string));
    
            var requestParameter = request != null ?
                new ObjectParameter("Request", request) :
                new ObjectParameter("Request", typeof(string));
    
            var accountParameter = account != null ?
                new ObjectParameter("Account", account) :
                new ObjectParameter("Account", typeof(string));
    
            var empIDParameter = empID.HasValue ?
                new ObjectParameter("EmpID", empID) :
                new ObjectParameter("EmpID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_GetHRRFReportByEmpIdPractice", practiceParameter, requestParameter, accountParameter, empIDParameter);
        }
    
        public virtual ObjectResult<sp_GetHRRFListByEmpIdPractice_Result> sp_GetHRRFListByEmpIdPractice(string practice, string request, string account, Nullable<int> empID)
        {
            var practiceParameter = practice != null ?
                new ObjectParameter("Practice", practice) :
                new ObjectParameter("Practice", typeof(string));
    
            var requestParameter = request != null ?
                new ObjectParameter("Request", request) :
                new ObjectParameter("Request", typeof(string));
    
            var accountParameter = account != null ?
                new ObjectParameter("Account", account) :
                new ObjectParameter("Account", typeof(string));
    
            var empIDParameter = empID.HasValue ?
                new ObjectParameter("EmpID", empID) :
                new ObjectParameter("EmpID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetHRRFListByEmpIdPractice_Result>("sp_GetHRRFListByEmpIdPractice", practiceParameter, requestParameter, accountParameter, empIDParameter);
        }
    
        public virtual ObjectResult<sp_GetHRRFListByEmpIdPracticeForBillingloss_Result> sp_GetHRRFListByEmpIdPracticeForBillingloss(string request, string criticality, Nullable<System.DateTime> fromDate, Nullable<System.DateTime> toDate)
        {
            var requestParameter = request != null ?
                new ObjectParameter("Request", request) :
                new ObjectParameter("Request", typeof(string));
    
            var criticalityParameter = criticality != null ?
                new ObjectParameter("Criticality", criticality) :
                new ObjectParameter("Criticality", typeof(string));
    
            var fromDateParameter = fromDate.HasValue ?
                new ObjectParameter("FromDate", fromDate) :
                new ObjectParameter("FromDate", typeof(System.DateTime));
    
            var toDateParameter = toDate.HasValue ?
                new ObjectParameter("ToDate", toDate) :
                new ObjectParameter("ToDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetHRRFListByEmpIdPracticeForBillingloss_Result>("sp_GetHRRFListByEmpIdPracticeForBillingloss", requestParameter, criticalityParameter, fromDateParameter, toDateParameter);
        }
    
        public virtual ObjectResult<sp_GetBillingLossList_Result> sp_GetBillingLossList(string criticality, Nullable<System.DateTime> fromDate, Nullable<System.DateTime> toDate)
        {
            var criticalityParameter = criticality != null ?
                new ObjectParameter("Criticality", criticality) :
                new ObjectParameter("Criticality", typeof(string));
    
            var fromDateParameter = fromDate.HasValue ?
                new ObjectParameter("FromDate", fromDate) :
                new ObjectParameter("FromDate", typeof(System.DateTime));
    
            var toDateParameter = toDate.HasValue ?
                new ObjectParameter("ToDate", toDate) :
                new ObjectParameter("ToDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetBillingLossList_Result>("sp_GetBillingLossList", criticalityParameter, fromDateParameter, toDateParameter);
        }
    
        public virtual ObjectResult<sp_GetBillingsLossList_Result> sp_GetBillingsLossList(string criticality, Nullable<System.DateTime> fromDate, Nullable<System.DateTime> toDate, string requestStatus)
        {
            var criticalityParameter = criticality != null ?
                new ObjectParameter("Criticality", criticality) :
                new ObjectParameter("Criticality", typeof(string));
    
            var fromDateParameter = fromDate.HasValue ?
                new ObjectParameter("FromDate", fromDate) :
                new ObjectParameter("FromDate", typeof(System.DateTime));
    
            var toDateParameter = toDate.HasValue ?
                new ObjectParameter("ToDate", toDate) :
                new ObjectParameter("ToDate", typeof(System.DateTime));
    
            var requestStatusParameter = requestStatus != null ?
                new ObjectParameter("RequestStatus", requestStatus) :
                new ObjectParameter("RequestStatus", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetBillingsLossList_Result>("sp_GetBillingsLossList", criticalityParameter, fromDateParameter, toDateParameter, requestStatusParameter);
        }
    
        public virtual ObjectResult<sp_GetProjectAllocations_Result> sp_GetProjectAllocations(string projectCode, string startDate)
        {
            var projectCodeParameter = projectCode != null ?
                new ObjectParameter("ProjectCode", projectCode) :
                new ObjectParameter("ProjectCode", typeof(string));
    
            var startDateParameter = startDate != null ?
                new ObjectParameter("StartDate", startDate) :
                new ObjectParameter("StartDate", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetProjectAllocations_Result>("sp_GetProjectAllocations", projectCodeParameter, startDateParameter);
        }
    
        public virtual ObjectResult<sp_GetProjectAllocationsSum_Result> sp_GetProjectAllocationsSum(string projectCode, string startDate)
        {
            var projectCodeParameter = projectCode != null ?
                new ObjectParameter("ProjectCode", projectCode) :
                new ObjectParameter("ProjectCode", typeof(string));
    
            var startDateParameter = startDate != null ?
                new ObjectParameter("StartDate", startDate) :
                new ObjectParameter("StartDate", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetProjectAllocationsSum_Result>("sp_GetProjectAllocationsSum", projectCodeParameter, startDateParameter);
        }
    
        public virtual int GetITSResourceDashBoardDetailsSummary(Nullable<int> employeeId)
        {
            var employeeIdParameter = employeeId.HasValue ?
                new ObjectParameter("employeeId", employeeId) :
                new ObjectParameter("employeeId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GetITSResourceDashBoardDetailsSummary", employeeIdParameter);
        }
    
        public virtual int sp_NumberingSystemGenerateNumber(string companyCode, string branchCode, string sequenceSuffix, Nullable<long> sequenceNumber, string typeCode, ObjectParameter result1)
        {
            var companyCodeParameter = companyCode != null ?
                new ObjectParameter("CompanyCode", companyCode) :
                new ObjectParameter("CompanyCode", typeof(string));
    
            var branchCodeParameter = branchCode != null ?
                new ObjectParameter("BranchCode", branchCode) :
                new ObjectParameter("BranchCode", typeof(string));
    
            var sequenceSuffixParameter = sequenceSuffix != null ?
                new ObjectParameter("SequenceSuffix", sequenceSuffix) :
                new ObjectParameter("SequenceSuffix", typeof(string));
    
            var sequenceNumberParameter = sequenceNumber.HasValue ?
                new ObjectParameter("SequenceNumber", sequenceNumber) :
                new ObjectParameter("SequenceNumber", typeof(long));
    
            var typeCodeParameter = typeCode != null ?
                new ObjectParameter("TypeCode", typeCode) :
                new ObjectParameter("TypeCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_NumberingSystemGenerateNumber", companyCodeParameter, branchCodeParameter, sequenceSuffixParameter, sequenceNumberParameter, typeCodeParameter, result1);
        }
    
        public virtual ObjectResult<GetClusterTeamMember_Result> GetClusterTeamMember()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetClusterTeamMember_Result>("GetClusterTeamMember");
        }
    
        public virtual ObjectResult<GetEmployeeLocation_Result> GetEmployeeLocation()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetEmployeeLocation_Result>("GetEmployeeLocation");
        }
    }
}
