//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trianz.Enterprise.Operations.EmployeeService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Employee", Namespace="http://schemas.datacontract.org/2004/07/Trianz.Enterprise.Services")]
    [System.SerializableAttribute()]
    public partial class Employee : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AssignmentStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BusinessGroupField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CostCenterField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CreatedByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> CreatedDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateOfBirthField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateOfJoinField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DesignationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EmployeeIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmployeeTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GenderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> GradeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsActiveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsServicingNoticePeriodField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsTravelReadyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LocationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LocationTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MasterSkillSetField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MiddleNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ModifiedByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> ModifiedDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PassportNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PracticeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> PreviousExperienceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PrimarySkillsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> ProjectManagerIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> RelievingDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReservationStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResourceStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SecondarySkillsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> SupervisorIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> UtilizationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VisaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AssignmentStatus {
            get {
                return this.AssignmentStatusField;
            }
            set {
                if ((object.ReferenceEquals(this.AssignmentStatusField, value) != true)) {
                    this.AssignmentStatusField = value;
                    this.RaisePropertyChanged("AssignmentStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BusinessGroup {
            get {
                return this.BusinessGroupField;
            }
            set {
                if ((object.ReferenceEquals(this.BusinessGroupField, value) != true)) {
                    this.BusinessGroupField = value;
                    this.RaisePropertyChanged("BusinessGroup");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CostCenter {
            get {
                return this.CostCenterField;
            }
            set {
                if ((object.ReferenceEquals(this.CostCenterField, value) != true)) {
                    this.CostCenterField = value;
                    this.RaisePropertyChanged("CostCenter");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CreatedBy {
            get {
                return this.CreatedByField;
            }
            set {
                if ((object.ReferenceEquals(this.CreatedByField, value) != true)) {
                    this.CreatedByField = value;
                    this.RaisePropertyChanged("CreatedBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> CreatedDate {
            get {
                return this.CreatedDateField;
            }
            set {
                if ((this.CreatedDateField.Equals(value) != true)) {
                    this.CreatedDateField = value;
                    this.RaisePropertyChanged("CreatedDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateOfBirth {
            get {
                return this.DateOfBirthField;
            }
            set {
                if ((this.DateOfBirthField.Equals(value) != true)) {
                    this.DateOfBirthField = value;
                    this.RaisePropertyChanged("DateOfBirth");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateOfJoin {
            get {
                return this.DateOfJoinField;
            }
            set {
                if ((this.DateOfJoinField.Equals(value) != true)) {
                    this.DateOfJoinField = value;
                    this.RaisePropertyChanged("DateOfJoin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Designation {
            get {
                return this.DesignationField;
            }
            set {
                if ((object.ReferenceEquals(this.DesignationField, value) != true)) {
                    this.DesignationField = value;
                    this.RaisePropertyChanged("Designation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EmployeeId {
            get {
                return this.EmployeeIdField;
            }
            set {
                if ((this.EmployeeIdField.Equals(value) != true)) {
                    this.EmployeeIdField = value;
                    this.RaisePropertyChanged("EmployeeId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmployeeType {
            get {
                return this.EmployeeTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.EmployeeTypeField, value) != true)) {
                    this.EmployeeTypeField = value;
                    this.RaisePropertyChanged("EmployeeType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Gender {
            get {
                return this.GenderField;
            }
            set {
                if ((object.ReferenceEquals(this.GenderField, value) != true)) {
                    this.GenderField = value;
                    this.RaisePropertyChanged("Gender");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Grade {
            get {
                return this.GradeField;
            }
            set {
                if ((this.GradeField.Equals(value) != true)) {
                    this.GradeField = value;
                    this.RaisePropertyChanged("Grade");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsActive {
            get {
                return this.IsActiveField;
            }
            set {
                if ((this.IsActiveField.Equals(value) != true)) {
                    this.IsActiveField = value;
                    this.RaisePropertyChanged("IsActive");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsServicingNoticePeriod {
            get {
                return this.IsServicingNoticePeriodField;
            }
            set {
                if ((this.IsServicingNoticePeriodField.Equals(value) != true)) {
                    this.IsServicingNoticePeriodField = value;
                    this.RaisePropertyChanged("IsServicingNoticePeriod");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsTravelReady {
            get {
                return this.IsTravelReadyField;
            }
            set {
                if ((this.IsTravelReadyField.Equals(value) != true)) {
                    this.IsTravelReadyField = value;
                    this.RaisePropertyChanged("IsTravelReady");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Location {
            get {
                return this.LocationField;
            }
            set {
                if ((object.ReferenceEquals(this.LocationField, value) != true)) {
                    this.LocationField = value;
                    this.RaisePropertyChanged("Location");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LocationType {
            get {
                return this.LocationTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.LocationTypeField, value) != true)) {
                    this.LocationTypeField = value;
                    this.RaisePropertyChanged("LocationType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MasterSkillSet {
            get {
                return this.MasterSkillSetField;
            }
            set {
                if ((object.ReferenceEquals(this.MasterSkillSetField, value) != true)) {
                    this.MasterSkillSetField = value;
                    this.RaisePropertyChanged("MasterSkillSet");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MiddleName {
            get {
                return this.MiddleNameField;
            }
            set {
                if ((object.ReferenceEquals(this.MiddleNameField, value) != true)) {
                    this.MiddleNameField = value;
                    this.RaisePropertyChanged("MiddleName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ModifiedBy {
            get {
                return this.ModifiedByField;
            }
            set {
                if ((object.ReferenceEquals(this.ModifiedByField, value) != true)) {
                    this.ModifiedByField = value;
                    this.RaisePropertyChanged("ModifiedBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> ModifiedDate {
            get {
                return this.ModifiedDateField;
            }
            set {
                if ((this.ModifiedDateField.Equals(value) != true)) {
                    this.ModifiedDateField = value;
                    this.RaisePropertyChanged("ModifiedDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PassportNumber {
            get {
                return this.PassportNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.PassportNumberField, value) != true)) {
                    this.PassportNumberField = value;
                    this.RaisePropertyChanged("PassportNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Practice {
            get {
                return this.PracticeField;
            }
            set {
                if ((object.ReferenceEquals(this.PracticeField, value) != true)) {
                    this.PracticeField = value;
                    this.RaisePropertyChanged("Practice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> PreviousExperience {
            get {
                return this.PreviousExperienceField;
            }
            set {
                if ((this.PreviousExperienceField.Equals(value) != true)) {
                    this.PreviousExperienceField = value;
                    this.RaisePropertyChanged("PreviousExperience");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PrimarySkills {
            get {
                return this.PrimarySkillsField;
            }
            set {
                if ((object.ReferenceEquals(this.PrimarySkillsField, value) != true)) {
                    this.PrimarySkillsField = value;
                    this.RaisePropertyChanged("PrimarySkills");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ProjectManagerId {
            get {
                return this.ProjectManagerIdField;
            }
            set {
                if ((this.ProjectManagerIdField.Equals(value) != true)) {
                    this.ProjectManagerIdField = value;
                    this.RaisePropertyChanged("ProjectManagerId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> RelievingDate {
            get {
                return this.RelievingDateField;
            }
            set {
                if ((this.RelievingDateField.Equals(value) != true)) {
                    this.RelievingDateField = value;
                    this.RaisePropertyChanged("RelievingDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReservationStatus {
            get {
                return this.ReservationStatusField;
            }
            set {
                if ((object.ReferenceEquals(this.ReservationStatusField, value) != true)) {
                    this.ReservationStatusField = value;
                    this.RaisePropertyChanged("ReservationStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ResourceStatus {
            get {
                return this.ResourceStatusField;
            }
            set {
                if ((object.ReferenceEquals(this.ResourceStatusField, value) != true)) {
                    this.ResourceStatusField = value;
                    this.RaisePropertyChanged("ResourceStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SecondarySkills {
            get {
                return this.SecondarySkillsField;
            }
            set {
                if ((object.ReferenceEquals(this.SecondarySkillsField, value) != true)) {
                    this.SecondarySkillsField = value;
                    this.RaisePropertyChanged("SecondarySkills");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> SupervisorId {
            get {
                return this.SupervisorIdField;
            }
            set {
                if ((this.SupervisorIdField.Equals(value) != true)) {
                    this.SupervisorIdField = value;
                    this.RaisePropertyChanged("SupervisorId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Utilization {
            get {
                return this.UtilizationField;
            }
            set {
                if ((this.UtilizationField.Equals(value) != true)) {
                    this.UtilizationField = value;
                    this.RaisePropertyChanged("Utilization");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Visa {
            get {
                return this.VisaField;
            }
            set {
                if ((object.ReferenceEquals(this.VisaField, value) != true)) {
                    this.VisaField = value;
                    this.RaisePropertyChanged("Visa");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="EmployeeService.IEmployeeService")]
    public interface IEmployeeService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeService/GetEmployees", ReplyAction="http://tempuri.org/IEmployeeService/GetEmployeesResponse")]
        Trianz.Enterprise.Operations.EmployeeService.Employee[] GetEmployees();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeService/GetEmployees", ReplyAction="http://tempuri.org/IEmployeeService/GetEmployeesResponse")]
        System.Threading.Tasks.Task<Trianz.Enterprise.Operations.EmployeeService.Employee[]> GetEmployeesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeService/GetEmployeeByID", ReplyAction="http://tempuri.org/IEmployeeService/GetEmployeeByIDResponse")]
        Trianz.Enterprise.Operations.EmployeeService.Employee GetEmployeeByID(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeService/GetEmployeeByID", ReplyAction="http://tempuri.org/IEmployeeService/GetEmployeeByIDResponse")]
        System.Threading.Tasks.Task<Trianz.Enterprise.Operations.EmployeeService.Employee> GetEmployeeByIDAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeService/GetEmployeeByEmail", ReplyAction="http://tempuri.org/IEmployeeService/GetEmployeeByEmailResponse")]
        Trianz.Enterprise.Operations.EmployeeService.Employee GetEmployeeByEmail(string emailid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeService/GetEmployeeByEmail", ReplyAction="http://tempuri.org/IEmployeeService/GetEmployeeByEmailResponse")]
        System.Threading.Tasks.Task<Trianz.Enterprise.Operations.EmployeeService.Employee> GetEmployeeByEmailAsync(string emailid);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IEmployeeServiceChannel : Trianz.Enterprise.Operations.EmployeeService.IEmployeeService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EmployeeServiceClient : System.ServiceModel.ClientBase<Trianz.Enterprise.Operations.EmployeeService.IEmployeeService>, Trianz.Enterprise.Operations.EmployeeService.IEmployeeService {
        
        public EmployeeServiceClient() {
        }
        
        public EmployeeServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EmployeeServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EmployeeServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EmployeeServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Trianz.Enterprise.Operations.EmployeeService.Employee[] GetEmployees() {
            return base.Channel.GetEmployees();
        }
        
        public System.Threading.Tasks.Task<Trianz.Enterprise.Operations.EmployeeService.Employee[]> GetEmployeesAsync() {
            return base.Channel.GetEmployeesAsync();
        }
        
        public Trianz.Enterprise.Operations.EmployeeService.Employee GetEmployeeByID(string id) {
            return base.Channel.GetEmployeeByID(id);
        }
        
        public System.Threading.Tasks.Task<Trianz.Enterprise.Operations.EmployeeService.Employee> GetEmployeeByIDAsync(string id) {
            return base.Channel.GetEmployeeByIDAsync(id);
        }
        
        public Trianz.Enterprise.Operations.EmployeeService.Employee GetEmployeeByEmail(string emailid) {
            return base.Channel.GetEmployeeByEmail(emailid);
        }
        
        public System.Threading.Tasks.Task<Trianz.Enterprise.Operations.EmployeeService.Employee> GetEmployeeByEmailAsync(string emailid) {
            return base.Channel.GetEmployeeByEmailAsync(emailid);
        }
    }
}
