//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trianz.Enterprise.Operations.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Candidate
    {
        public int CandidateID { get; set; }
        public string TRNumber { get; set; }
        public string CandidateNumber { get; set; }
        public string CandidateName { get; set; }
        public string EmailID { get; set; }
        public string PhoneNumber { get; set; }
        public string Address { get; set; }
        public string CompanyDetails { get; set; }
        public string NoticePeriod { get; set; }
        public string YearofExperience { get; set; }
        public string CurrentRole { get; set; }
        public string ReportingTo { get; set; }
        public Nullable<decimal> CurrentSalary { get; set; }
        public Nullable<decimal> CurrentVariablePay { get; set; }
        public Nullable<decimal> ExpectedSalary { get; set; }
        public string CurrentCity { get; set; }
        public string PreferredCity { get; set; }
        public Nullable<decimal> OfferedValue { get; set; }
        public Nullable<decimal> VariablePay { get; set; }
        public Nullable<System.DateTime> JoiningDate { get; set; }
        public string DocumentName { get; set; }
        public string ContentType { get; set; }
        public Nullable<decimal> DocumentSize { get; set; }
        public byte[] DocumentContent { get; set; }
        public Nullable<int> PrevInterviewStatus { get; set; }
        public Nullable<int> CurrentInterviewStatus { get; set; }
        public string Approve_Reject { get; set; }
        public string status { get; set; }
        public string Password { get; set; }
        public Nullable<bool> RelocationCostInvolved { get; set; }
        public string RelocationCostApproval { get; set; }
        public string JoiningBonusApproval { get; set; }
        public Nullable<decimal> JoiningBonusAmt { get; set; }
        public string Qualication { get; set; }
        public string Tier_1_2_3_ { get; set; }
        public Nullable<int> ResumeSource { get; set; }
        public string ResumeSubSource { get; set; }
    }
}
