//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trianz.Enterprise.Operations.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CareersUsersExperienced
    {
        public Nullable<int> TotalExperience_Yrs { get; set; }
        public Nullable<int> TotalExperience_Mnths { get; set; }
        public string PrimarySkill { get; set; }
        public string SecondarySkill { get; set; }
        public string PreferredLocation { get; set; }
        public Nullable<int> NoticePeriod_Days { get; set; }
        public string Visa { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public int Id { get; set; }
        public int User_Id { get; set; }
        public string TRNumber { get; set; }
    }
}
