//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trianz.Enterprise.Operations.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DelegateEmployee
    {
        public int DelegateId { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public string Department { get; set; }
        public Nullable<int> DelegateSupervisorId { get; set; }
        public string Comment { get; set; }
    }
}
