//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trianz.Enterprise.Operations.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeSkillHistory
    {
        public int HistoryID { get; set; }
        public int EMployeeID { get; set; }
        public int SkillID { get; set; }
        public string Expertiselevel { get; set; }
        public string TechnologyLastUsed { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string UpdateStatus { get; set; }
        public string Comments { get; set; }
        public Nullable<int> SkillIDOld { get; set; }
        public string ExpertiselevelOld { get; set; }
        public string TechnologyLastUsedOld { get; set; }
        public string PreviousStatus { get; set; }
        public Nullable<int> ApproverID { get; set; }
        public Nullable<System.DateTime> ApprovalDate { get; set; }
    }
}
