//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trianz.Enterprise.Operations.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeProfile
    {
        public long EmployeID { get; set; }
        public string HRRFNumber { get; set; }
        public string YearsOfExpinYears { get; set; }
        public string YearsOfExpinMonths { get; set; }
        public string ProfileStatus { get; set; }
        public string AssignmentStatus { get; set; }
        public string ProfileTitle { get; set; }
        public string FilePath { get; set; }
    }
}
