//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trianz.Enterprise.Operations.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employee()
        {
            this.AddtionalWHMPunchInOUTs = new HashSet<AddtionalWHMPunchInOUT>();
            this.EmployeeSkills = new HashSet<EmployeeSkill>();
        }
    
        public int EmployeeId { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string UserName { get; set; }
        public string Email { get; set; }
        public string Gender { get; set; }
        public Nullable<int> Grade { get; set; }
        public string LocationType { get; set; }
        public string Location { get; set; }
        public string EmployeeType { get; set; }
        public string Designation { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public System.DateTime DateOfJoin { get; set; }
        public Nullable<int> PreviousExperience { get; set; }
        public string PassportNumber { get; set; }
        public string Visa { get; set; }
        public string BusinessGroup { get; set; }
        public string CostCenter { get; set; }
        public string Practice { get; set; }
        public string MasterSkillSet { get; set; }
        public string PrimarySkills { get; set; }
        public string SecondarySkills { get; set; }
        public string ResourceStatus { get; set; }
        public string ReservationStatus { get; set; }
        public string AssignmentStatus { get; set; }
        public Nullable<int> SupervisorId { get; set; }
        public Nullable<int> ProjectManagerId { get; set; }
        public Nullable<int> Utilization { get; set; }
        public Nullable<bool> IsServicingNoticePeriod { get; set; }
        public Nullable<bool> IsTravelReady { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> RelievingDate { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
        public string SPOC { get; set; }
        public string Project { get; set; }
        public Nullable<System.DateTime> ProsedStartDate { get; set; }
        public Nullable<System.DateTime> ProsedEndDate { get; set; }
        public byte[] Resumes { get; set; }
        public string MobileNumber { get; set; }
        public string PARENT_ORG { get; set; }
        public byte[] ResumePdf { get; set; }
        public string Region { get; set; }
        public string PermanentAddress { get; set; }
        public string HighestDegree { get; set; }
        public Nullable<decimal> TrianzExp { get; set; }
        public string JobName { get; set; }
        public string Track { get; set; }
        public string ParentLocation { get; set; }
        public string PrimaryPractice { get; set; }
        public string SecondaryPractice { get; set; }
        public Nullable<int> BUHR { get; set; }
        public string EntityName { get; set; }
        public Nullable<bool> BirthdayMailerFlag { get; set; }
        public Nullable<bool> AnniversaryMailerFlag { get; set; }
        public string GradeCode { get; set; }
        public Nullable<int> NoticePeriod { get; set; }
        public string FusionResignationSync { get; set; }
        public string PersonalEmail { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AddtionalWHMPunchInOUT> AddtionalWHMPunchInOUTs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeeSkill> EmployeeSkills { get; set; }
    }
}
