//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trianz.Enterprise.Operations.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeSkill
    {
        public long Id { get; set; }
        public Nullable<int> EmployeeId { get; set; }
        public Nullable<bool> IsPrimary { get; set; }
        public Nullable<long> Skills { get; set; }
        public Nullable<int> Rating { get; set; }
        public string SkillDescription { get; set; }
        public string Status { get; set; }
        public string Remarks { get; set; }
        public string EmployeeName { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual MasterLookUp MasterLookUp { get; set; }
    }
}
