//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trianz.Enterprise.Operations.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeAddressInformation
    {
        public int EmpAddressInfoID { get; set; }
        public int EmployeeId { get; set; }
        public string EmployeeName { get; set; }
        public string CurrentLocation { get; set; }
        public string BaseLocation { get; set; }
        public string CubicleNumber { get; set; }
        public string PrimaryMobileNumber { get; set; }
        public string SecondaryMobileNumber { get; set; }
        public string EmergencyContactPersonName { get; set; }
        public string EmergencyContactPersonRelationship { get; set; }
        public string EmergencyContactPersonMobileNumber { get; set; }
        public string CurrentAddressDoorNo { get; set; }
        public string CurrentAddressStreet { get; set; }
        public string CurrentAddressArea { get; set; }
        public string CurrentAddressCity { get; set; }
        public string CurrentAddressState { get; set; }
        public string CurrentAddressCountry { get; set; }
        public string PermanentAddressDoorNo { get; set; }
        public string PermanentAddressStreet { get; set; }
        public string PermanentAddressArea { get; set; }
        public string PermanentAddressCity { get; set; }
        public string PermanentAddressState { get; set; }
        public string PermanentAddressCountry { get; set; }
        public string CurrentAddressPostalCode { get; set; }
        public string PermanentAddressPostalCode { get; set; }
    }
}
