//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trianz.Enterprise.Operations.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExternalHire
    {
        public int ExternalHireId { get; set; }
        public string Name { get; set; }
        public string RequestStatus { get; set; }
        public string FulfilmentRemarks { get; set; }
        public Nullable<System.DateTime> DOJ { get; set; }
        public Nullable<System.DateTime> FulfilmentDate { get; set; }
        public string CancellationReason { get; set; }
        public string HRRFNumber { get; set; }
        public Nullable<long> HRRFId { get; set; }
        public Nullable<System.DateTime> CancelDate { get; set; }
        public Nullable<int> EmployeeId { get; set; }
        public string RecruiterName { get; set; }
        public string DuplicateHRRFNo { get; set; }
    
        public virtual HRRF HRRF { get; set; }
    }
}
