//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trianz.Enterprise.Operations.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Menus
    {
        public int MenuID { get; set; }
        public string PageName { get; set; }
        public string Controller { get; set; }
        public string ActionMethod { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string Role { get; set; }
    }
}
