//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trianz.Enterprise.Operations.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotificationTo
    {
        public int NotificationToID { get; set; }
        public Nullable<int> NotificationID { get; set; }
        public string NotificationTo1 { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ApplicationCode { get; set; }
    }
}
