//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trianz.Enterprise.Operations.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notification
    {
        public long NotificationID { get; set; }
        public string NotificationType { get; set; }
        public Nullable<System.DateTime> NotificationDate { get; set; }
        public Nullable<int> NotificationFrom { get; set; }
        public Nullable<int> NotificationTo { get; set; }
        public string NotificationMessage { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string AssetID { get; set; }
        public string ApplicationCode { get; set; }
        public Nullable<bool> IsEmailSent { get; set; }
        public string CC { get; set; }
        public string BCC { get; set; }
        public Nullable<bool> IsFromGroupID { get; set; }
        public string FromGroupID { get; set; }
    }
}
