//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trianz.Enterprise.Operations.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Opportunity
    {
        public int potentialid { get; set; }
        public string potential_no { get; set; }
        public string potentialname { get; set; }
        public string sales_Stage { get; set; }
        public string RelatedTo { get; set; }
        public string PrimaryPractice { get; set; }
        public string AssignedTo { get; set; }
        public string ServiceLine { get; set; }
        public string ServiceType { get; set; }
        public string ClientSponsorName { get; set; }
        public string ClientSponsorTitle { get; set; }
        public string NextStep { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string BDGroup { get; set; }
        public Nullable<System.DateTime> ExpectedCloseDate { get; set; }
        public Nullable<int> LBLAction { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
    }
}
