//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trianz.Enterprise.Operations.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PerformanceFeedback
    {
        public long FeedbackId { get; set; }
        public string FeedbackPeriod { get; set; }
        public int EmployeeId { get; set; }
        public int ManagerId { get; set; }
        public string FeedbackSummary { get; set; }
        public Nullable<bool> IsFeedbackEmailSent { get; set; }
        public Nullable<System.DateTime> FeedbackEmailSentDate { get; set; }
        public Nullable<bool> IsFeedbackAccepted { get; set; }
        public Nullable<System.DateTime> FeedbackAcceptedDate { get; set; }
        public string EmployeeComment { get; set; }
        public Nullable<System.DateTime> FeedbackDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string Status { get; set; }
        public Nullable<int> Rating { get; set; }
    }
}
