//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trianz.Enterprise.Operations.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectAssignmenthistory
    {
        public int HistoryID { get; set; }
        public int AssignmentId { get; set; }
        public string ProjectName { get; set; }
        public int ProjectID { get; set; }
        public Nullable<int> EmployeeId { get; set; }
        public string ProjectCode { get; set; }
        public Nullable<System.DateTime> StartDateOld { get; set; }
        public Nullable<System.DateTime> EnddateOld { get; set; }
        public Nullable<int> UtilizationOld { get; set; }
        public Nullable<bool> IsActiveOld { get; set; }
        public string Assigned_ByOld { get; set; }
        public string BillingStatusOld { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> modifiedBy { get; set; }
        public Nullable<System.DateTime> StartDateNew { get; set; }
        public Nullable<System.DateTime> EndDateNew { get; set; }
        public Nullable<int> UtilizationNew { get; set; }
        public Nullable<bool> IsActiveNew { get; set; }
        public string Assigned_byNew { get; set; }
        public string BillingStatusNew { get; set; }
    }
}
