//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trianz.Enterprise.Operations.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectAssignment_BackUP
    {
        public int Assignment_Id { get; set; }
        public string ProjectName { get; set; }
        public int ProjectID { get; set; }
        public Nullable<int> EmployeeId { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<int> Utilization { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string Assigned_By { get; set; }
        public Nullable<System.DateTime> Assigned_Date { get; set; }
        public string ProjectCode { get; set; }
        public string BillingStatus { get; set; }
    }
}
