//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trianz.Enterprise.Operations.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRTCSKILLCLUSTER
    {
        public int PRTCSKILLID { get; set; }
        public string PRACTICE { get; set; }
        public string SKILLCLUSTER { get; set; }
        public string CSKILLS { get; set; }
        public string SKILLCODE { get; set; }
    }
}
