//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trianz.Enterprise.Operations.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResourceRelease
    {
        public int Release_Id { get; set; }
        public Nullable<int> EmployeeId { get; set; }
        public string EmployeeName { get; set; }
        public string ProjectDesignation { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<int> Utilization { get; set; }
        public string ProjectCode { get; set; }
        public string ClientorProject { get; set; }
        public string ReasonForRelease { get; set; }
        public Nullable<bool> IsDiscResourceOnProject { get; set; }
        public string SkillsGoodAt { get; set; }
        public string DetailedFeedBack { get; set; }
        public string ResourcePerformance { get; set; }
    }
}
