//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trianz.Enterprise.Operations.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoleGroupMaster
    {
        public int RoleGroupId { get; set; }
        public string RoleGroupName { get; set; }
        public string Title { get; set; }
        public string Experience { get; set; }
        public Nullable<int> Grade { get; set; }
        public Nullable<int> DisciplineId { get; set; }
        public string Practice { get; set; }
    }
}
