//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trianz.Enterprise.Operations.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShiftallowanceItem
    {
        public string ShiftTiming { get; set; }
        public string ShiftName { get; set; }
        public string ProjectCode { get; set; }
        public int EmployeeId { get; set; }
        public int ApproverId { get; set; }
        public bool Mon { get; set; }
        public bool Tue { get; set; }
        public bool Wed { get; set; }
        public bool Thu { get; set; }
        public bool Fri { get; set; }
        public bool Sat { get; set; }
        public bool Sun { get; set; }
        public string ItemStatus { get; set; }
        public int Shiftallowanceid { get; set; }
        public int Shiftallowanceitemid { get; set; }
    }
}
