//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trianz.Enterprise.Operations.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SkillMaster
    {
        public int SkillId { get; set; }
        public string SkillCategory { get; set; }
        public string Skillset { get; set; }
        public string Practice { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
