//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trianz.Enterprise.Operations.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SKILLSCORE
    {
        public int SKILLID { get; set; }
        public string PRACTICE { get; set; }
        public string GRADE { get; set; }
        public string ROLEGROUP { get; set; }
        public string SKILLS { get; set; }
        public string TechincalPanel { get; set; }
    }
}
