//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trianz.Enterprise.Operations.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SKILLCLSTRJD_Delete
    {
        public int SKILLCLSTRID { get; set; }
        public string SKILLCODE { get; set; }
        public string CLSTRDESC { get; set; }
        public string CLSTRJD { get; set; }
        public Nullable<int> CLSTRJDVER { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
