//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trianz.Enterprise.Operations.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TempDashboard
    {
        public int HRRF { get; set; }
        public string Role { get; set; }
        public string Grade { get; set; }
        public string Skills { get; set; }
        public string Practice { get; set; }
        public string Location { get; set; }
        public string Account { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
