//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trianz.Enterprise.Operations.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Timesheet
    {
        public long TimesheetID { get; set; }
        public System.DateTime FromDate { get; set; }
        public System.DateTime ToDate { get; set; }
        public string TimesheetWeek { get; set; }
        public Nullable<decimal> TotalHours { get; set; }
        public Nullable<int> EmployeeId { get; set; }
        public Nullable<int> ProjectManagerID { get; set; }
        public Nullable<int> ApprovedBy { get; set; }
        public string ProjectCode { get; set; }
        public string Status { get; set; }
        public string Comments { get; set; }
        public Nullable<System.DateTime> syncdate { get; set; }
        public bool IsAdjustmentMode { get; set; }
        public Nullable<int> SupervisorId { get; set; }
    }
}
