//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trianz.Enterprise.Operations.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TZ_CorporateOperationsEntities : DbContext
    {
        public TZ_CorporateOperationsEntities()
            : base("name=TZ_CorporateOperationsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Application> Applications { get; set; }
        public virtual DbSet<ApplicationSetting> ApplicationSettings { get; set; }
        public virtual DbSet<EmployeeProfile> EmployeeProfiles { get; set; }
        public virtual DbSet<ExternalFulfillment> ExternalFulfillments { get; set; }
        public virtual DbSet<HRRF> HRRFs { get; set; }
        public virtual DbSet<HRRFHistory> HRRFHistories { get; set; }
        public virtual DbSet<ProposeAssociate> ProposeAssociates { get; set; }
        public virtual DbSet<MasterLookUp> MasterLookUps { get; set; }
    }
}
